package manisha.khatri.newsanytime.util;

public enum NewsCategory {
    INTERNATIONAL, INTERNATIONAL_SPORTS, INTERNATIONAL_BUSINESS, INTERNATIONAL_ENTERTAINMENT,
    NATIONAL, NATIONAL_SPORTS, NATIONAL_BUSINESS, NATIONAL_ENTERTAINMENT, TOP_STORIES,
    SEARCHED_NEWS
}
